import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Disclaimer",
  description:
    "Disclaimer for Paycheck & COL Hub. Important information about the limitations of our salary and cost of living calculators.",
};

const LAST_UPDATED = "April 1, 2026";
const METHODOLOGY_SUMMARY = `Our calculators use published tax tables and typical social contribution rules for each jurisdiction. We default to single-filer assumptions with no additional deductions; cost-of-living indices are blended from public datasets and market reports. See the About page for full source links and a detailed methodology.`;

export default function DisclaimerPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6">
      <h1 className="text-3xl font-bold text-slate-900">Disclaimer</h1>
      <p className="mt-2 text-slate-600">Last updated: {LAST_UPDATED}</p>
      <p className="text-sm text-slate-500">
        Methodology and data sources are summarized below; see About for full
        details.
      </p>

      <div className="prose prose-slate mt-10 max-w-none space-y-8 text-slate-700">
        <section>
          <h2 className="text-xl font-semibold text-slate-900">
            1. General Information Only
          </h2>
          <p>
            The information provided on Paycheck &amp; COL Hub (the
            &quot;Service&quot;), including all salary calculations, tax
            estimates, cost-of-living comparisons, and editorial content, is for
            general informational and educational purposes only. It is not
            intended to be, and should not be construed as, professional tax,
            financial, legal, accounting, or career advice.
          </p>
          <p>
            You should not act or refrain from acting based solely on the
            information provided by this Service. Always consult a qualified tax
            advisor, financial planner, accountant, or attorney for advice
            tailored to your specific circumstances before making any financial
            or relocation decisions.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-900">
            2. Estimates, Not Exact Figures
          </h2>
          <p>
            All results generated by our calculators—including net salary, tax
            breakdowns, cost-of-living equivalents, and job offer
            comparisons—are <strong>estimates</strong>. They are based on
            simplified assumptions, including but not limited to:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Single-filer tax status with no dependents</li>
            <li>
              No additional deductions or credits (e.g., 401(k) contributions,
              HSA, child tax credit, mortgage interest, student loan interest)
            </li>
            <li>No additional income (e.g., freelance, investment, rental)</li>
            <li>Standard personal allowance where applicable</li>
            <li>
              No salary sacrifice or pension contributions beyond defaults
            </li>
          </ul>
          <p>
            Your actual tax liability, take-home pay, and cost of living may
            differ significantly based on your personal situation, filing
            status, deductions, credits, employer benefits, and other factors.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-900">
            Methodology Summary
          </h2>
          <p>{METHODOLOGY_SUMMARY}</p>
          <p>
            For full methodology, data sources, and our update history, see the{" "}
            <a
              href="/about"
              className="text-teal-700 underline hover:no-underline"
            >
              About
            </a>{" "}
            page.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-900">
            3. Data Accuracy and Timeliness
          </h2>
          <p>
            We strive to keep our tax brackets, social contribution rates, and
            cost-of-living data accurate and up to date. Our data is sourced
            from official government publications (e.g.,{" "}
            <a
              href="https://www.irs.gov/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-teal-700 underline hover:no-underline"
            >
              IRS
            </a>
            ,{" "}
            <a
              href="https://www.gov.uk/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-teal-700 underline hover:no-underline"
            >
              HMRC / GOV.UK
            </a>
            ,{" "}
            <a
              href="https://www.bundesfinanzministerium.de/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-teal-700 underline hover:no-underline"
            >
              German Federal Ministry of Finance
            </a>
            ) and publicly available economic data.
          </p>
          <p>
            However, tax laws and rates change frequently. We do{" "}
            <strong>not</strong> guarantee that the data on this site is
            accurate, complete, or current at all times. It may contain errors
            or omissions. For the most authoritative and up-to-date tax
            information, always refer directly to the official tax authority in
            your jurisdiction.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-900">
            4. No Professional Relationship
          </h2>
          <p>
            Using the Service does not create a professional-client relationship
            of any kind (including, but not limited to, an accountant-client,
            attorney-client, or financial advisor-client relationship) between
            you and Paycheck &amp; COL Hub or its operators. We are not licensed
            tax professionals, financial advisors, or attorneys, and we do not
            hold ourselves out as such.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-900">
            5. Third-Party Links and Content
          </h2>
          <p>
            The Service may contain links to third-party websites (e.g.,
            government tax authorities, external resources). These links are
            provided for convenience and reference only. We do not endorse,
            control, or accept responsibility for the content, accuracy, or
            practices of any third-party website.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-900">
            6. Advertising Disclosure
          </h2>
          <p>
            Paycheck &amp; COL Hub is a free service supported by advertising.
            We use Google AdSense, which may display personalized or
            non-personalized advertisements on our pages. Google and its
            partners may use cookies and other tracking technologies to serve
            ads based on your interests and browsing history.
          </p>
          <p>
            Advertising revenue helps us keep our tools and content free for all
            users. Advertisements on this site do not constitute endorsements by
            Paycheck &amp; COL Hub. The presence of advertising does not
            influence our calculations, editorial content, or the results
            displayed by our tools.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-900">
            7. Limitation of Liability
          </h2>
          <p>
            To the fullest extent permitted by applicable law, Paycheck &amp;
            COL Hub and its operators shall not be liable for any direct,
            indirect, incidental, special, consequential, or punitive
            damages—including lost profits, lost data, or any other
            losses—arising from your use of or reliance on the Service or any
            information provided on it. Use the Service at your own risk.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-900">
            8. Changes to This Disclaimer
          </h2>
          <p>
            We may update this Disclaimer from time to time. Changes will be
            posted on this page with an updated &quot;Last updated&quot; date.
            Your continued use of the Service after any changes constitutes
            acceptance of the revised Disclaimer.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-900">
            9. Contact Us
          </h2>
          <p>
            If you have questions about this Disclaimer, please contact us via
            our{" "}
            <Link
              href="/contact"
              className="text-teal-700 underline hover:no-underline"
            >
              Contact
            </Link>{" "}
            page. For more about how we handle your data, see our{" "}
            <Link
              href="/privacy"
              className="text-teal-700 underline hover:no-underline"
            >
              Privacy Policy
            </Link>
            . For our full terms, see our{" "}
            <Link
              href="/terms"
              className="text-teal-700 underline hover:no-underline"
            >
              Terms of Use
            </Link>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
